# Generated by Django 4.2.5 on 2023-09-08 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleBudget', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='categorymaxspend',
            unique_together={('category', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('name', 'user')},
        ),
    ]
