# Generated by Django 4.2.5 on 2023-09-11 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleBudget', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='SimpleBudget.category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='subCategory',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='SimpleBudget.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subCategories', to='SimpleBudget.category'),
        ),
    ]
